name: Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: node-16-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: ls -la
      - name: setup
        run: npm run setup:ci
      - name: npm install
        run: npm ci
      - name: dist
        run: npm run dist
      - name: out
        run: bash scripts/pkg.ba.sh
